version: '3.8'
services:
  webdis:
    image: nicolas/webdis:0.1.20
    container_name: webdis
    restart: always
    ports:
      - '7379:7379'
    networks:
      - share-network

networks:
  share-network:
    external: true