version: '3'
services:   
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    command: [start-kafka.sh]
    expose:
      - "8080"
      - "9092"
    networks:
      - share-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS : PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR : 1
    # volumes:
    #   - kafka_kafka:/opt/kafka_2.12-2.4.1/logs

  jobmanager:
    image: apache/flink
    container_name: jobmanager
    command: "jobmanager.sh start-foreground"
    ports:
      - 8081:8081
    networks:
      - share-network
    volumes:
      - ./flink/conf:/opt/flink/conf
      - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
      - ./flink/workspace:/opt/flink/workspace
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: apache/flink
    container_name: taskmanager
    depends_on:
      - jobmanager
    networks:
      - share-network
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./flink/conf:/opt/flink/conf
      - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager


volumes:
  kafka_kafka:

networks:
  share-network:
    external: true
