version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
    networks:
      - share-network
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - ./nifi/workspace/selenium/downloads:/home/seluser/Downloads

networks:
  share-network:
    external: true
