version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - share-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0 # stabele version (the latest version has some issues)
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - share-network
    environment:
      # mongo auth
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=$ME_CONFIG_MONGODB_SERVER
      # mongo express auth
      - ME_CONFIG_BASICAUTH=$ME_CONFIG_BASICAUTH
      - ME_CONFIG_BASICAUTH_USERNAME=$ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$ME_CONFIG_BASICAUTH_PASSWORD

# Define named volumes
volumes:
  mongo-data:
    driver: local
    
networks:
  share-network:
    external: true

