version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"
    networks:
      - share-network
    volumes:
      - kafka_zookeeper:/opt/zookeeper-3.4.13/data
      
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    command: [start-kafka.sh]
    expose:
      - "8080"
      - "9092"
    networks:
      - share-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS : PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR : 1
    volumes:
      - kafka_kafka:/opt/kafka_2.12-2.4.1/logs

volumes:
  kafka_kafka:
  kafka_zookeeper:

networks:
  share-network:
    external: true
