# ================================== General ===================================
name: "charisma-machine"
tags: ["windows", "os"]

# ================================== Other ===================================
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

# metricbeat.autodiscover:
#   providers:
#     - type: docker # also it can be kubernetes
#       hints.enabled: false # we enabled hints based autodiscover feature (read here https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html)

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  fields:
    kafka_topic: docker-container
    charisma_field: "data-engineers"
  fields_under_root: true
- module: docker
  metricsets:
    - "cpu"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  fields:
    kafka_topic: docker-cpu
    charisma_field: "we-are-here"
  fields_under_root: true

output.kafka:
  hosts: ["kafka-elk:9094"]
  topic: "logs-%{[kafka_topic]}-%{[charisma_field]}"
  key: "%{[agent.name]}" # let's define our message's key
  partition.hash:
    reachable_only: false
    hash: [] # what is partition hash? If it's empty our key is used
